bin: some scripts converted to my standard script format

diff --git a/bin/bin/httpserver b/bin/bin/httpserver
--- a/bin/bin/httpserver
+++ b/bin/bin/httpserver
@@ -53,24 +53,59 @@ _print_version() {
 	echo "${script} version ${version}"
 }
 
-port="8080"
-open_with_browser=false
-while [[ $# -gt 0 ]]; do
-	case $1 in
-		-o|--open-with-browser) open_with_browser=true; shift ;;
-		-v|--version) _print_version; exit ;;
-		-h|--help) _print_help; exit ;;
-		*) port="$1"; shift ;;
-	esac
-done
+_parse_arguments() {
+	port="8080"
+	open_with_browser=false
 
-first_digit=$(( port / 1000 ))
-if [[ $first_digit -eq 0 ]]; then
-	echo "${script}: invalid port number \`${port}\`" >&2
-	echo "Try '${script} --help' for more information."
-	exit 1
-fi
+	while [[ $# -gt 0 ]]; do
+		case $1 in
+			-o|--open-with-browser) open_with_browser=true; shift ;;
+			-v|--version) _print_version; exit ;;
+			-h|--help) _print_help; exit ;;
+			*) port="$1"; shift ;;
+		esac
+	done
 
-$open_with_browser && sleep 1 && xdg-open "http://localhost:${port}/"
+	first_digit=$(( port / 1000 ))
+	if [[ $first_digit -eq 0 ]]; then
+		echo "${script}: invalid port number \`${port}\`" >&2
+		echo "Try '${script} --help' for more information."
+		exit 1
+	fi
+}
 
-python "${script_directory}/httpserver.py" "$port"
+main() {
+  _parse_arguments "$@"
+
+	$open_with_browser && sleep 1 && xdg-open "http://localhost:${port}/"
+
+	python <<-EOF
+	import SimpleHTTPServer
+	import SocketServer
+	import os
+
+	PORT=${port}
+
+	map = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map
+	map[""] = "text/plain"
+
+	for key, value in map.items():
+	  map[key] = value + ";charset=UTF-8"
+
+	handler = SimpleHTTPServer.SimpleHTTPRequestHandler
+	httpd = SocketServer.TCPServer(("", PORT), handler)
+
+	print "httpserver: directory", os.getcwd(), "serving at", PORT
+	print "httpserver: press CTRL+C to kill server"
+
+	try:
+	  print "httpserver: logs"
+	  print "----------------"
+	  httpd.serve_forever()
+	except (KeyboardInterrupt, SystemExit):
+	  print "----------------"
+	  print "httpserver: killed server"
+	EOF
+}
+
+main "$@"
diff --git a/bin/bin/man2pdf b/bin/bin/man2pdf
--- a/bin/bin/man2pdf
+++ b/bin/bin/man2pdf
@@ -49,13 +49,21 @@ _print_version() {
 	echo "${script} version ${version}"
 }
 
-[[ "$1" =~ ^(-v|--version)$ ]] && _print_version && exit
-[[ "$1" =~ ^(-help|--help)$ ]] && _print_help && exit
+_parse_arguments() {
+	[[ "$1" =~ ^(-v|--version)$ ]] && _print_version && exit
+	[[ "$1" =~ ^(-help|--help)$ ]] && _print_help && exit
 
-if [[ -z "$1" ]]; then
-	echo "${script}: missing operand" >&2
-	echo "Try '${script} --help' for more information."
-	exit 1
-fi
+	if [[ -z "$1" ]]; then
+		echo "${script}: missing operand" >&2
+		echo "Try '${script} --help' for more information."
+		exit 1
+	fi
+}
 
-man -t "$1" | ps2pdf - "$1.pdf"
+main() {
+	_parse_arguments "$@"
+
+	man -t "$1" | ps2pdf - "$1.pdf"
+}
+
+main "$@"
diff --git a/bin/bin/phpserver b/bin/bin/phpserver
--- a/bin/bin/phpserver
+++ b/bin/bin/phpserver
@@ -51,24 +51,33 @@ _print_version() {
 	echo "${script} version ${version}"
 }
 
-port="4000"
-open_with_browser=false
-while [[ $# -gt 0 ]]; do
-	case $1 in
-		-o|--open-with-browser) open_with_browser=true; shift ;;
-		-v|--version) _print_version; exit ;;
-		-h|--help) _print_help; exit ;;
-		*) port="$1"; shift ;;
-	esac
-done
+_parse_arguments() {
+	port="4000"
+	open_with_browser=false
 
-first_digit=$(( port / 1000 ))
-if [[ $first_digit -eq 0 ]]; then
-	echo "${script}: $port: invalid port number" >&2
-	echo "Try '${script} --help' for more information."
-	exit 1
-fi
+	while [[ $# -gt 0 ]]; do
+		case $1 in
+			-o|--open-with-browser) open_with_browser=true; shift ;;
+			-v|--version) _print_version; exit ;;
+			-h|--help) _print_help; exit ;;
+			*) port="$1"; shift ;;
+		esac
+	done
 
-$open_with_browser && sleep 1 && xdg-open "http://localhost:${port}/"
+	first_digit=$(( port / 1000 ))
+	if [[ $first_digit -eq 0 ]]; then
+		echo "${script}: $port: invalid port number" >&2
+		echo "Try '${script} --help' for more information."
+		exit 1
+	fi
+}
 
-php -S "127.0.0.1:${port}"
+main() {
+	_parse_arguments "$@"
+
+	$open_with_browser && sleep 1 && xdg-open "http://localhost:${port}/"
+
+	php -S "127.0.0.1:${port}"
+}
+
+main "$@"
diff --git a/bin/bin/you2mp3 b/bin/bin/you2mp3
--- a/bin/bin/you2mp3
+++ b/bin/bin/you2mp3
@@ -37,7 +37,7 @@ readonly version="1.0.0"
 _print_help() {
 	cat <<-EOF
 	Usage: ${script} [OPTIONS] YOUTUBE_URL
-	Download YouTube video as mp3 audio file.
+	Download YouTube video as MP3 audio file.
 
 	Options:
 	  -v, --version    Show ${script} version number
@@ -49,20 +49,28 @@ _print_version() {
 	echo "${script} version ${version}"
 }
 
-[[ "$1" =~ ^(-v|--version)$ ]] && _print_version && exit
-[[ "$1" =~ ^(-h|--help)$ ]] && _print_help && exit
+_parse_arguments() {
+	[[ "$1" =~ ^(-v|--version)$ ]] && _print_version && exit
+	[[ "$1" =~ ^(-h|--help)$ ]] && _print_help && exit
 
-if [[ ! "$1" =~ ^(http)s?:\/\/youtu(be)?\.(com|be) ]]; then
-	echo "${script}: invalid youtube url \`${1}\`" >&2
-	exit 1
-fi
+	if [[ ! "$1" =~ ^(http)s?:\/\/youtu(be)?\.(com|be) ]]; then
+		echo "${script}: invalid youtube url \`${1}\`" >&2
+		exit 1
+	fi
+}
 
-url="$1"
-output_directory="${home}/Music/YouTube/%(title)s.%(ext)s"
-format="bestaudio"
-ext="mp3"
+main() {
+	_parse_arguments "$@"
 
-youtube-dl --extract-audio --audio-format "$ext" \
-					 -f "$format" \
-					 -o "$output_directory" \
-					 "$url"
+	url="$1"
+	output_directory="${home}/Music/YouTube/%(title)s.%(ext)s"
+	format="bestaudio"
+	ext="mp3"
+
+	youtube-dl --extract-audio --audio-format "$ext" \
+						 -f "$format" \
+						 -o "$output_directory" \
+						 "$url"
+}
+
+main "$@"
